### ISSUE TITLE
During installation, I click "Select your drive" and click "ok" on the popup, it loops back to the patreon information screen...

### ISSUE THREAD

**Issue by ajcroteau** [EmuDeck/emudeck-electron-early#1]
Using my ASUS ROG Ally...

During installation on version 2.1.18, after entering my patreon information and then selecting either easy or custom mode, and then I click "Select your drive" and click "ok" on the "this will take a few seconds..." popup. It loops back to where I entered my patreon information and continues to loop back each time I get to the drive selection screen after I click "ok" on the popup.

I do have Sophos anti-virus installed on my ally, could that be causing an issue?

**Comment by Tikaran** [comment]
I am having this same issue.

**Comment by ajcroteau** [comment]
Confirmed fixed... please close this issue :)
