### ISSUE TITLE
Installing dependencies 

### ISSUE THREAD

**Issue by Examsxx** [EmuDeck/emudeck-electron-early#4]
Downloaded emu deck for rog ally 2.1.21 and it wont even start downloading GIT or 7Zip ive reinstalled tried older versions same thing
![20231014_201516](https://github.com/EmuDeck/emudeck-electron-early/assets/147955765/bac9b4eb-0c24-4ad2-ae16-c7d51ea7aff1)
![20231014_201516](https://github.com/EmuDeck/emudeck-electron-early/assets/147955765/274a9a17-f438-4957-a7ab-9340bf2642a8)

**Comment by dragoonDorise** [comment]
@Examsxx 

Did you install EmuDeck using the .bat?
